//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapWinGIS.MainProgram {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MapWinGIS.MainProgram.GlobalResource", typeof(GlobalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bookmark_manager {
            get {
                object obj = ResourceManager.GetObject("bookmark_manager", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bookmarks_view {
            get {
                object obj = ResourceManager.GetObject("bookmarks_view", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap charts_properties {
            get {
                object obj = ResourceManager.GetObject("charts_properties", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap deselect {
            get {
                object obj = ResourceManager.GetObject("deselect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap deselect_all {
            get {
                object obj = ResourceManager.GetObject("deselect_all", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap documentation {
            get {
                object obj = ResourceManager.GetObject("documentation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap export_georeferenced {
            get {
                object obj = ResourceManager.GetObject("export_georeferenced", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap export_map {
            get {
                object obj = ResourceManager.GetObject("export_map", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon formlegend {
            get {
                object obj = ResourceManager.GetObject("formlegend", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap group_collapse {
            get {
                object obj = ResourceManager.GetObject("group_collapse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap group_expand {
            get {
                object obj = ResourceManager.GetObject("group_expand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap group_open {
            get {
                object obj = ResourceManager.GetObject("group_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgAdd {
            get {
                object obj = ResourceManager.GetObject("imgAdd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgBookmarkAdd {
            get {
                object obj = ResourceManager.GetObject("imgBookmarkAdd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgBookmarkDelete {
            get {
                object obj = ResourceManager.GetObject("imgBookmarkDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgBookmarkView {
            get {
                object obj = ResourceManager.GetObject("imgBookmarkView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgClose {
            get {
                object obj = ResourceManager.GetObject("imgClose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgCollapseAll {
            get {
                object obj = ResourceManager.GetObject("imgCollapseAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgCopy {
            get {
                object obj = ResourceManager.GetObject("imgCopy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgCopyLegend {
            get {
                object obj = ResourceManager.GetObject("imgCopyLegend", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgDelete {
            get {
                object obj = ResourceManager.GetObject("imgDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgDown {
            get {
                object obj = ResourceManager.GetObject("imgDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgExpandAll {
            get {
                object obj = ResourceManager.GetObject("imgExpandAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgExport {
            get {
                object obj = ResourceManager.GetObject("imgExport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgFlash {
            get {
                object obj = ResourceManager.GetObject("imgFlash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgFolder {
            get {
                object obj = ResourceManager.GetObject("imgFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgGroupAdd {
            get {
                object obj = ResourceManager.GetObject("imgGroupAdd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgGroupRemove {
            get {
                object obj = ResourceManager.GetObject("imgGroupRemove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgHelp {
            get {
                object obj = ResourceManager.GetObject("imgHelp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgHistory {
            get {
                object obj = ResourceManager.GetObject("imgHistory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgInfo {
            get {
                object obj = ResourceManager.GetObject("imgInfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgKeyboard {
            get {
                object obj = ResourceManager.GetObject("imgKeyboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgLabel {
            get {
                object obj = ResourceManager.GetObject("imgLabel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgLayerAdd {
            get {
                object obj = ResourceManager.GetObject("imgLayerAdd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgLayerClear {
            get {
                object obj = ResourceManager.GetObject("imgLayerClear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgLayerRemove {
            get {
                object obj = ResourceManager.GetObject("imgLayerRemove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgMap {
            get {
                object obj = ResourceManager.GetObject("imgMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgMapExtents {
            get {
                object obj = ResourceManager.GetObject("imgMapExtents", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgMapPreview {
            get {
                object obj = ResourceManager.GetObject("imgMapPreview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgMapScale {
            get {
                object obj = ResourceManager.GetObject("imgMapScale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgMetadata {
            get {
                object obj = ResourceManager.GetObject("imgMetadata", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgNew {
            get {
                object obj = ResourceManager.GetObject("imgNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgOpenGroup {
            get {
                object obj = ResourceManager.GetObject("imgOpenGroup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgPlugin {
            get {
                object obj = ResourceManager.GetObject("imgPlugin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgPluginDisabled {
            get {
                object obj = ResourceManager.GetObject("imgPluginDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgPluginEdit {
            get {
                object obj = ResourceManager.GetObject("imgPluginEdit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgPluginSub {
            get {
                object obj = ResourceManager.GetObject("imgPluginSub", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgPrinter {
            get {
                object obj = ResourceManager.GetObject("imgPrinter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgProperties {
            get {
                object obj = ResourceManager.GetObject("imgProperties", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgRelabel {
            get {
                object obj = ResourceManager.GetObject("imgRelabel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgSave {
            get {
                object obj = ResourceManager.GetObject("imgSave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgSaveAs {
            get {
                object obj = ResourceManager.GetObject("imgSaveAs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgScale {
            get {
                object obj = ResourceManager.GetObject("imgScale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgScripts {
            get {
                object obj = ResourceManager.GetObject("imgScripts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgSettings {
            get {
                object obj = ResourceManager.GetObject("imgSettings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgTableEditor {
            get {
                object obj = ResourceManager.GetObject("imgTableEditor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgUp {
            get {
                object obj = ResourceManager.GetObject("imgUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgUpdate {
            get {
                object obj = ResourceManager.GetObject("imgUpdate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgWelcome {
            get {
                object obj = ResourceManager.GetObject("imgWelcome", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgZoomExtent {
            get {
                object obj = ResourceManager.GetObject("imgZoomExtent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgZoomToLayer {
            get {
                object obj = ResourceManager.GetObject("imgZoomToLayer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap label_properties {
            get {
                object obj = ResourceManager.GetObject("label_properties", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap label_reload {
            get {
                object obj = ResourceManager.GetObject("label_reload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap language {
            get {
                object obj = ResourceManager.GetObject("language", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layer_add {
            get {
                object obj = ResourceManager.GetObject("layer_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layer_add_ecwp {
            get {
                object obj = ResourceManager.GetObject("layer_add_ecwp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layer_categories {
            get {
                object obj = ResourceManager.GetObject("layer_categories", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layer_properties {
            get {
                object obj = ResourceManager.GetObject("layer_properties", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layer_query {
            get {
                object obj = ResourceManager.GetObject("layer_query", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layer_remove {
            get {
                object obj = ResourceManager.GetObject("layer_remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layer_symbology {
            get {
                object obj = ResourceManager.GetObject("layer_symbology", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap legend {
            get {
                object obj = ResourceManager.GetObject("legend", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Legend 的本地化字符串。
        /// </summary>
        internal static string LegendName_Text {
            get {
                return ResourceManager.GetString("LegendName_Text", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap mantis {
            get {
                object obj = ResourceManager.GetObject("mantis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap map_export {
            get {
                object obj = ResourceManager.GetObject("map_export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon MapPanel {
            get {
                object obj = ResourceManager.GetObject("MapPanel", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 关于(&amp;A)... 的本地化字符串。
        /// </summary>
        internal static string mnuAboutMapWindow_Text {
            get {
                return ResourceManager.GetString("mnuAboutMapWindow_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加ECWP图层(&amp;A) 的本地化字符串。
        /// </summary>
        internal static string mnuAddECWPLayer_Text {
            get {
                return ResourceManager.GetString("mnuAddECWPLayer_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加图层(&amp;A) 的本地化字符串。
        /// </summary>
        internal static string mnuAddLayer_Text {
            get {
                return ResourceManager.GetString("mnuAddLayer_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加书签(&amp;A) 的本地化字符串。
        /// </summary>
        internal static string mnuBookmarkAdd_Text {
            get {
                return ResourceManager.GetString("mnuBookmarkAdd_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 书签(&amp;B) 的本地化字符串。
        /// </summary>
        internal static string mnuBookmarks_Text {
            get {
                return ResourceManager.GetString("mnuBookmarks_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 书签管理(&amp;M) 的本地化字符串。
        /// </summary>
        internal static string mnuBookmarksManager_Text {
            get {
                return ResourceManager.GetString("mnuBookmarksManager_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看书签(&amp;V) 的本地化字符串。
        /// </summary>
        internal static string mnuBookmarkView_Text {
            get {
                return ResourceManager.GetString("mnuBookmarkView_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交bug(&amp;B) 的本地化字符串。
        /// </summary>
        internal static string mnuBugReport_Text {
            get {
                return ResourceManager.GetString("mnuBugReport_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查更新(&amp;R) 的本地化字符串。
        /// </summary>
        internal static string mnuCheckUpdates_Text {
            get {
                return ResourceManager.GetString("mnuCheckUpdates_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简体中文 的本地化字符串。
        /// </summary>
        internal static string mnuChinese_Text {
            get {
                return ResourceManager.GetString("mnuChinese_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空全部选择(&amp;K) 的本地化字符串。
        /// </summary>
        internal static string mnuClearAllSelection_Text {
            get {
                return ResourceManager.GetString("mnuClearAllSelection_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空所有图层(&amp;L) 的本地化字符串。
        /// </summary>
        internal static string mnuClearLayer_Text {
            get {
                return ResourceManager.GetString("mnuClearLayer_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除预览(&amp;P) 的本地化字符串。
        /// </summary>
        internal static string mnuClearPreview_Text {
            get {
                return ResourceManager.GetString("mnuClearPreview_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空当前层选择的Shapes(&amp;K) 的本地化字符串。
        /// </summary>
        internal static string mnuClearSelectedShapes_Text {
            get {
                return ResourceManager.GetString("mnuClearSelectedShapes_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助内容(&amp;C) 的本地化字符串。
        /// </summary>
        internal static string mnuContents_Text {
            get {
                return ResourceManager.GetString("mnuContents_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制(&amp;C) 的本地化字符串。
        /// </summary>
        internal static string mnuCopy_Text {
            get {
                return ResourceManager.GetString("mnuCopy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图符(Legend)(&amp;L) 的本地化字符串。
        /// </summary>
        internal static string mnuCopyLegend_Text {
            get {
                return ResourceManager.GetString("mnuCopyLegend_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地图(&amp;M) 的本地化字符串。
        /// </summary>
        internal static string mnuCopyMap_Text {
            get {
                return ResourceManager.GetString("mnuCopyMap_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 方向针(&amp;N) 的本地化字符串。
        /// </summary>
        internal static string mnuCopyNorthArrow_Text {
            get {
                return ResourceManager.GetString("mnuCopyNorthArrow_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 范围条(&amp;S) 的本地化字符串。
        /// </summary>
        internal static string mnuCopyScaleBar_Text {
            get {
                return ResourceManager.GetString("mnuCopyScaleBar_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑插件(&amp;E) 的本地化字符串。
        /// </summary>
        internal static string mnuEditPlugins_Text {
            get {
                return ResourceManager.GetString("mnuEditPlugins_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        internal static string mnuEnglish_Text {
            get {
                return ResourceManager.GetString("mnuEnglish_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出(&amp;E) 的本地化字符串。
        /// </summary>
        internal static string mnuExit_Text {
            get {
                return ResourceManager.GetString("mnuExit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地图输出(&amp;O) 的本地化字符串。
        /// </summary>
        internal static string mnuExport_Text {
            get {
                return ResourceManager.GetString("mnuExport_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助(&amp;H) 的本地化字符串。
        /// </summary>
        internal static string mnuHelp_Text {
            get {
                return ResourceManager.GetString("mnuHelp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言(&amp;L) 的本地化字符串。
        /// </summary>
        internal static string mnuLanguages_Text {
            get {
                return ResourceManager.GetString("mnuLanguages_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图层(&amp;L) 的本地化字符串。
        /// </summary>
        internal static string mnuLayer_Text {
            get {
                return ResourceManager.GetString("mnuLayer_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性数据表(&amp;T) 的本地化字符串。
        /// </summary>
        internal static string mnuLayerAttributeTable_Text {
            get {
                return ResourceManager.GetString("mnuLayerAttributeTable_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shapefile Categories(&amp;M) 的本地化字符串。
        /// </summary>
        internal static string mnuLayerCategories_Text {
            get {
                return ResourceManager.GetString("mnuLayerCategories_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图表属性(&amp;C) 的本地化字符串。
        /// </summary>
        internal static string mnuLayerCharts_Text {
            get {
                return ResourceManager.GetString("mnuLayerCharts_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签属性(&amp;P) 的本地化字符串。
        /// </summary>
        internal static string mnuLayerLabels_Text {
            get {
                return ResourceManager.GetString("mnuLayerLabels_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图层属性(&amp;L) 的本地化字符串。
        /// </summary>
        internal static string mnuLayerProperties_Text {
            get {
                return ResourceManager.GetString("mnuLayerProperties_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签重载(&amp;R) 的本地化字符串。
        /// </summary>
        internal static string mnuLayerRelabel_Text {
            get {
                return ResourceManager.GetString("mnuLayerRelabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建(&amp;N) 的本地化字符串。
        /// </summary>
        internal static string mnuNew_Text {
            get {
                return ResourceManager.GetString("mnuNew_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前进缩放(&amp;U) 的本地化字符串。
        /// </summary>
        internal static string mnuNextZoom_Text {
            get {
                return ResourceManager.GetString("mnuNextZoom_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地文档(&amp;L) 的本地化字符串。
        /// </summary>
        internal static string mnuOfflineDocs_Text {
            get {
                return ResourceManager.GetString("mnuOfflineDocs_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在线文档(&amp;O) 的本地化字符串。
        /// </summary>
        internal static string mnuOnlineDocs_Text {
            get {
                return ResourceManager.GetString("mnuOnlineDocs_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开(&amp;O) 的本地化字符串。
        /// </summary>
        internal static string mnuOpen_Text {
            get {
                return ResourceManager.GetString("mnuOpen_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从新的组中打开项目(&amp;G) 的本地化字符串。
        /// </summary>
        internal static string mnuOpenProjectIntoGroup_Text {
            get {
                return ResourceManager.GetString("mnuOpenProjectIntoGroup_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 符号管理(&amp;S) 的本地化字符串。
        /// </summary>
        internal static string mnuOptionsManager_Text {
            get {
                return ResourceManager.GetString("mnuOptionsManager_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗口(&amp;F) 的本地化字符串。
        /// </summary>
        internal static string mnuPanels_Text {
            get {
                return ResourceManager.GetString("mnuPanels_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件(&amp;P) 的本地化字符串。
        /// </summary>
        internal static string mnuPlugins_Text {
            get {
                return ResourceManager.GetString("mnuPlugins_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传插件(&amp;U) 的本地化字符串。
        /// </summary>
        internal static string mnuPluginUpLoading_Text {
            get {
                return ResourceManager.GetString("mnuPluginUpLoading_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预览地图(&amp;P) 的本地化字符串。
        /// </summary>
        internal static string mnuPreview_Text {
            get {
                return ResourceManager.GetString("mnuPreview_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后退缩放(&amp;B) 的本地化字符串。
        /// </summary>
        internal static string mnuPreviousZoom_Text {
            get {
                return ResourceManager.GetString("mnuPreviousZoom_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印(&amp;P) 的本地化字符串。
        /// </summary>
        internal static string mnuPrint_Text {
            get {
                return ResourceManager.GetString("mnuPrint_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件(&amp;F) 的本地化字符串。
        /// </summary>
        internal static string mnuProject_Text {
            get {
                return ResourceManager.GetString("mnuProject_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目设置(&amp;C) 的本地化字符串。
        /// </summary>
        internal static string mnuProjectSettings_Text {
            get {
                return ResourceManager.GetString("mnuProjectSettings_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建查询(&amp;Q) 的本地化字符串。
        /// </summary>
        internal static string mnuQueryLayer_Text {
            get {
                return ResourceManager.GetString("mnuQueryLayer_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 近期项目(&amp;L) 的本地化字符串。
        /// </summary>
        internal static string mnuRecentProjects_Text {
            get {
                return ResourceManager.GetString("mnuRecentProjects_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除该组 的本地化字符串。
        /// </summary>
        internal static string mnuRemoveGroup_Text {
            get {
                return ResourceManager.GetString("mnuRemoveGroup_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除图层(&amp;D) 的本地化字符串。
        /// </summary>
        internal static string mnuRemoveLayer_Text {
            get {
                return ResourceManager.GetString("mnuRemoveLayer_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存(&amp;S) 的本地化字符串。
        /// </summary>
        internal static string mnuSave_Text {
            get {
                return ResourceManager.GetString("mnuSave_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 另存为(&amp;A) 的本地化字符串。
        /// </summary>
        internal static string mnuSaveAs_Text {
            get {
                return ResourceManager.GetString("mnuSaveAs_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地理引用的地图(&amp;G) 的本地化字符串。
        /// </summary>
        internal static string mnuSaveGeorefMapImage_Text {
            get {
                return ResourceManager.GetString("mnuSaveGeorefMapImage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Legend(&amp;L) 的本地化字符串。
        /// </summary>
        internal static string mnuSaveLegend_Text {
            get {
                return ResourceManager.GetString("mnuSaveLegend_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地图(&amp;M) 的本地化字符串。
        /// </summary>
        internal static string mnuSaveMapImage_Text {
            get {
                return ResourceManager.GetString("mnuSaveMapImage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 方向针(&amp;N) 的本地化字符串。
        /// </summary>
        internal static string mnuSaveNorthArrow_Text {
            get {
                return ResourceManager.GetString("mnuSaveNorthArrow_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 范围条(&amp;S) 的本地化字符串。
        /// </summary>
        internal static string mnuSaveScaleBar_Text {
            get {
                return ResourceManager.GetString("mnuSaveScaleBar_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 脚本(&amp;S) 的本地化字符串。
        /// </summary>
        internal static string mnuScript_Text {
            get {
                return ResourceManager.GetString("mnuScript_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置比例(&amp;R) 的本地化字符串。
        /// </summary>
        internal static string mnuSetScale_Text {
            get {
                return ResourceManager.GetString("mnuSetScale_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快捷键(&amp;S) 的本地化字符串。
        /// </summary>
        internal static string mnuShortcuts_Text {
            get {
                return ResourceManager.GetString("mnuShortcuts_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Legend(&amp;L) 的本地化字符串。
        /// </summary>
        internal static string mnuShowLegend_Text {
            get {
                return ResourceManager.GetString("mnuShowLegend_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预览地图(&amp;P) 的本地化字符串。
        /// </summary>
        internal static string mnuShowPreviewMap_Text {
            get {
                return ResourceManager.GetString("mnuShowPreviewMap_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示浮动比例尺(&amp;S) 的本地化字符串。
        /// </summary>
        internal static string mnuShowScaleBar_Text {
            get {
                return ResourceManager.GetString("mnuShowScaleBar_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新手指导(&amp;G) 的本地化字符串。
        /// </summary>
        internal static string mnuTutorials_Text {
            get {
                return ResourceManager.GetString("mnuTutorials_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前视图(&amp;C) 的本地化字符串。
        /// </summary>
        internal static string mnuUpdatePreviewCurr_Text {
            get {
                return ResourceManager.GetString("mnuUpdatePreviewCurr_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全图视图(&amp;E) 的本地化字符串。
        /// </summary>
        internal static string mnuUpdatePreviewFull_Text {
            get {
                return ResourceManager.GetString("mnuUpdatePreviewFull_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视图(&amp;V) 的本地化字符串。
        /// </summary>
        internal static string mnuView_Text {
            get {
                return ResourceManager.GetString("mnuView_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎界面(&amp;W) 的本地化字符串。
        /// </summary>
        internal static string mnuWelcomeScreen_Text {
            get {
                return ResourceManager.GetString("mnuWelcomeScreen_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 放大(&amp;I) 的本地化字符串。
        /// </summary>
        internal static string mnuZoomIn_Text {
            get {
                return ResourceManager.GetString("mnuZoomIn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩小(&amp;O) 的本地化字符串。
        /// </summary>
        internal static string mnuZoomOut_Text {
            get {
                return ResourceManager.GetString("mnuZoomOut_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复位(&amp;F) 的本地化字符串。
        /// </summary>
        internal static string mnuZoomToFullExtents_Text {
            get {
                return ResourceManager.GetString("mnuZoomToFullExtents_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩放至组 的本地化字符串。
        /// </summary>
        internal static string mnuZoomToGroup_Text {
            get {
                return ResourceManager.GetString("mnuZoomToGroup_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩放至图层 的本地化字符串。
        /// </summary>
        internal static string mnuZoomToLayer_Text {
            get {
                return ResourceManager.GetString("mnuZoomToLayer_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同步PreviewMap(&amp;Y) 的本地化字符串。
        /// </summary>
        internal static string mnuZoomToPreviewExtents_Text {
            get {
                return ResourceManager.GetString("mnuZoomToPreviewExtents_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 谢谢！您的数据提交成功。 的本地化字符串。
        /// </summary>
        internal static string msgDataSubmitted_Text {
            get {
                return ResourceManager.GetString("msgDataSubmitted_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该项目中的一个图层没有找到，无法定位的文件是:{0}  您希望手动定位这个文件吗？ No,将从该项目中卸载该图层. Cancel,将卸载所有无法找到的图层. 的本地化字符串。
        /// </summary>
        internal static string msgDropMissingLayer_Text {
            get {
                return ResourceManager.GetString("msgDropMissingLayer_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到图层;{0} 的本地化字符串。
        /// </summary>
        internal static string msgDropMissingLayer_Title {
            get {
                return ResourceManager.GetString("msgDropMissingLayer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你确定要移除当前选择的层吗？ 的本地化字符串。
        /// </summary>
        internal static string msgHandleShortcutKeys_Text {
            get {
                return ResourceManager.GetString("msgHandleShortcutKeys_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 面积: 的本地化字符串。
        /// </summary>
        internal static string msgPanelArea_Text {
            get {
                return ResourceManager.GetString("msgPanelArea_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 距离: 的本地化字符串。
        /// </summary>
        internal static string msgPanelDistance_Text {
            get {
                return ResourceManager.GetString("msgPanelDistance_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目文件无法保存，因为没有足够的权限。请给与{0}足够的权限。 的本地化字符串。
        /// </summary>
        internal static string msgProjectInsufficientAccess_Text {
            get {
                return ResourceManager.GetString("msgProjectInsufficientAccess_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限限制 的本地化字符串。
        /// </summary>
        internal static string msgProjectInsufficientAccess_Title {
            get {
                return ResourceManager.GetString("msgProjectInsufficientAccess_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目文件无法保存，因为该文件是ReadOnly。请设置{0}文件具有读写权限。 的本地化字符串。
        /// </summary>
        internal static string msgProjectReadOnly_Text {
            get {
                return ResourceManager.GetString("msgProjectReadOnly_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目文件只读 的本地化字符串。
        /// </summary>
        internal static string msgProjectReadOnly_Title {
            get {
                return ResourceManager.GetString("msgProjectReadOnly_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将本次修改保存到 的本地化字符串。
        /// </summary>
        internal static string msgSaveProject1_Text {
            get {
                return ResourceManager.GetString("msgSaveProject1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本项目？ 的本地化字符串。
        /// </summary>
        internal static string msgSaveProject2_Text {
            get {
                return ResourceManager.GetString("msgSaveProject2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Down Arrow - 向下移动地图(视野的25%) 的本地化字符串。
        /// </summary>
        internal static string msgShortcutsArrowDown_Text {
            get {
                return ResourceManager.GetString("msgShortcutsArrowDown_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left Arrow - 向左移动地图(视野的25%) 的本地化字符串。
        /// </summary>
        internal static string msgShortcutsArrowLeft_Text {
            get {
                return ResourceManager.GetString("msgShortcutsArrowLeft_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right Arrow - 向右移动地图(视野的25%) 的本地化字符串。
        /// </summary>
        internal static string msgShortcutsArrowRight_Text {
            get {
                return ResourceManager.GetString("msgShortcutsArrowRight_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Up Arrow - 向上移动地图(视野的25%) 的本地化字符串。
        /// </summary>
        internal static string msgShortcutsArrowUp_Text {
            get {
                return ResourceManager.GetString("msgShortcutsArrowUp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BackSpace : 返回到上一次操作 的本地化字符串。
        /// </summary>
        internal static string msgShortcutsBackspace_Text {
            get {
                return ResourceManager.GetString("msgShortcutsBackspace_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctrl+UP, Ctrl+Down : 在Legend中转换选择的层  的本地化字符串。
        /// </summary>
        internal static string msgShortcutsCtrlArrows_Text {
            get {
                return ResourceManager.GetString("msgShortcutsCtrlArrows_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctrl+C - 复制当前地图图像到剪贴板 的本地化字符串。
        /// </summary>
        internal static string msgShortcutsCtrlC_Text {
            get {
                return ResourceManager.GetString("msgShortcutsCtrlC_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctrl+Enter : 图层属性 的本地化字符串。
        /// </summary>
        internal static string msgShortcutsCtrlEnter_Text {
            get {
                return ResourceManager.GetString("msgShortcutsCtrlEnter_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctrl+F4 - 关闭当前的项目 的本地化字符串。
        /// </summary>
        internal static string msgShortcutsCtrlF4_Text {
            get {
                return ResourceManager.GetString("msgShortcutsCtrlF4_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctrl+H - 选择Shape/高亮显示该选择区域 的本地化字符串。
        /// </summary>
        internal static string msgShortcutsCtrlH_Text {
            get {
                return ResourceManager.GetString("msgShortcutsCtrlH_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctrl+Home - 移动到当前选择的层 的本地化字符串。
        /// </summary>
        internal static string msgShortcutsCtrlHome_Text {
            get {
                return ResourceManager.GetString("msgShortcutsCtrlHome_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctrl+I - 进入地图放大模式 的本地化字符串。
        /// </summary>
        internal static string msgShortcutsCtrlI_Text {
            get {
                return ResourceManager.GetString("msgShortcutsCtrlI_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctrl+M - 进入移动地图模式 的本地化字符串。
        /// </summary>
        internal static string msgShortcutsCtrlM_Text {
            get {
                return ResourceManager.GetString("msgShortcutsCtrlM_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctrl+O - 进入地图缩小模式 的本地化字符串。
        /// </summary>
        internal static string msgShortcutsCtrlO_Text {
            get {
                return ResourceManager.GetString("msgShortcutsCtrlO_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctrl+P - 打印 的本地化字符串。
        /// </summary>
        internal static string msgShortcutsCtrlP_Text {
            get {
                return ResourceManager.GetString("msgShortcutsCtrlP_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctrl+R - 复位 的本地化字符串。
        /// </summary>
        internal static string msgShortcutsCtrlR_Text {
            get {
                return ResourceManager.GetString("msgShortcutsCtrlR_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctrl+S - 保存项目 的本地化字符串。
        /// </summary>
        internal static string msgShortcutsCtrlS_Text {
            get {
                return ResourceManager.GetString("msgShortcutsCtrlS_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctrl+Shift+I - 特征标识符模式 的本地化字符串。
        /// </summary>
        internal static string msgShortcutsCtrlShiftI_Text {
            get {
                return ResourceManager.GetString("msgShortcutsCtrlShiftI_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctrl+Shift+O - 打开一个项目 的本地化字符串。
        /// </summary>
        internal static string msgShortcutsCtrlShiftO_Text {
            get {
                return ResourceManager.GetString("msgShortcutsCtrlShiftO_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctrl+Space : 在图层上启动可见性 的本地化字符串。
        /// </summary>
        internal static string msgShortcutsCtrlSpace_Text {
            get {
                return ResourceManager.GetString("msgShortcutsCtrlSpace_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctrl+Y - 前进 的本地化字符串。
        /// </summary>
        internal static string msgShortcutsCtrlY_Text {
            get {
                return ResourceManager.GetString("msgShortcutsCtrlY_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctrl+Z - 后退 的本地化字符串。
        /// </summary>
        internal static string msgShortcutsCtrlZ_Text {
            get {
                return ResourceManager.GetString("msgShortcutsCtrlZ_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete - 移除当前选择的图层 的本地化字符串。
        /// </summary>
        internal static string msgShortcutsDel_Text {
            get {
                return ResourceManager.GetString("msgShortcutsDel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home - 复位 的本地化字符串。
        /// </summary>
        internal static string msgShortcutsHome_Text {
            get {
                return ResourceManager.GetString("msgShortcutsHome_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert - 添加一个图层 的本地化字符串。
        /// </summary>
        internal static string msgShortcutsIns_Text {
            get {
                return ResourceManager.GetString("msgShortcutsIns_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minus - 以屏幕中心为基点缩小(视野的25%) 的本地化字符串。
        /// </summary>
        internal static string msgShortcutsMinus_Text {
            get {
                return ResourceManager.GetString("msgShortcutsMinus_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PageDown - 向下移动地图(视野的50%) 的本地化字符串。
        /// </summary>
        internal static string msgShortcutsPageDown_Text {
            get {
                return ResourceManager.GetString("msgShortcutsPageDown_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PageUp - 向上移动地图(视野的50%) 的本地化字符串。
        /// </summary>
        internal static string msgShortcutsPageUp_Text {
            get {
                return ResourceManager.GetString("msgShortcutsPageUp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plus - 以屏幕中心为基点放大(视野的25%) 的本地化字符串。
        /// </summary>
        internal static string msgShortcutsPlus_Text {
            get {
                return ResourceManager.GetString("msgShortcutsPlus_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可用快捷键如下： 的本地化字符串。
        /// </summary>
        internal static string msgShortcutsTitle_Text {
            get {
                return ResourceManager.GetString("msgShortcutsTitle_Text", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap northArrow {
            get {
                object obj = ResourceManager.GetObject("northArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap open {
            get {
                object obj = ResourceManager.GetObject("open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pan {
            get {
                object obj = ResourceManager.GetObject("pan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap panels {
            get {
                object obj = ResourceManager.GetObject("panels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap paypal {
            get {
                object obj = ResourceManager.GetObject("paypal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 作 者: 的本地化字符串。
        /// </summary>
        internal static string PluginPropertyAuthor_Text {
            get {
                return ResourceManager.GetString("PluginPropertyAuthor_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时 间: 的本地化字符串。
        /// </summary>
        internal static string PluginPropertyBuildDate_Text {
            get {
                return ResourceManager.GetString("PluginPropertyBuildDate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描 述: 的本地化字符串。
        /// </summary>
        internal static string PluginPropertyDescription_Text {
            get {
                return ResourceManager.GetString("PluginPropertyDescription_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名 称: 的本地化字符串。
        /// </summary>
        internal static string PluginPropertyName_Text {
            get {
                return ResourceManager.GetString("PluginPropertyName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版 本: 的本地化字符串。
        /// </summary>
        internal static string PluginPropertyVersion_Text {
            get {
                return ResourceManager.GetString("PluginPropertyVersion_Text", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap print {
            get {
                object obj = ResourceManager.GetObject("print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap project {
            get {
                object obj = ResourceManager.GetObject("project", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap project_settings {
            get {
                object obj = ResourceManager.GetObject("project_settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap quit {
            get {
                object obj = ResourceManager.GetObject("quit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap recent_maps {
            get {
                object obj = ResourceManager.GetObject("recent_maps", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap remove_all_layers {
            get {
                object obj = ResourceManager.GetObject("remove_all_layers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save_as {
            get {
                object obj = ResourceManager.GetObject("save_as", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap saveNew {
            get {
                object obj = ResourceManager.GetObject("saveNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 改变单位 的本地化字符串。
        /// </summary>
        internal static string sbContextMenu_ChangeUnits_Text {
            get {
                return ResourceManager.GetString("sbContextMenu_ChangeUnits_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择背景颜色 的本地化字符串。
        /// </summary>
        internal static string sbContextMenu_ChooseBackcolor_Text {
            get {
                return ResourceManager.GetString("sbContextMenu_ChooseBackcolor_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择字体颜色 的本地化字符串。
        /// </summary>
        internal static string sbContextMenu_ChooseForecolor_Text {
            get {
                return ResourceManager.GetString("sbContextMenu_ChooseForecolor_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左下角显示 的本地化字符串。
        /// </summary>
        internal static string sbContextMenu_LowerLeft_Text {
            get {
                return ResourceManager.GetString("sbContextMenu_LowerLeft_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右下角显示 的本地化字符串。
        /// </summary>
        internal static string sbContextMenu_LowerRight_Text {
            get {
                return ResourceManager.GetString("sbContextMenu_LowerRight_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左上角显示 的本地化字符串。
        /// </summary>
        internal static string sbContextMenu_UpperLeft_Text {
            get {
                return ResourceManager.GetString("sbContextMenu_UpperLeft_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右上角显示 的本地化字符串。
        /// </summary>
        internal static string sbContextMenu_UpperRight_Text {
            get {
                return ResourceManager.GetString("sbContextMenu_UpperRight_Text", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap scale_bar {
            get {
                object obj = ResourceManager.GetObject("scale_bar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap scale_bar_add {
            get {
                object obj = ResourceManager.GetObject("scale_bar_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap selectNew {
            get {
                object obj = ResourceManager.GetObject("selectNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap set_map_scale {
            get {
                object obj = ResourceManager.GetObject("set_map_scale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap splashPic {
            get {
                object obj = ResourceManager.GetObject("splashPic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap table_editor {
            get {
                object obj = ResourceManager.GetObject("table_editor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tutorials {
            get {
                object obj = ResourceManager.GetObject("tutorials", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap welcome {
            get {
                object obj = ResourceManager.GetObject("welcome", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom_extentNew {
            get {
                object obj = ResourceManager.GetObject("zoom_extentNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom_inNew {
            get {
                object obj = ResourceManager.GetObject("zoom_inNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom_lastNew {
            get {
                object obj = ResourceManager.GetObject("zoom_lastNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom_layerNew {
            get {
                object obj = ResourceManager.GetObject("zoom_layerNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom_nextNew {
            get {
                object obj = ResourceManager.GetObject("zoom_nextNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom_outNew {
            get {
                object obj = ResourceManager.GetObject("zoom_outNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom_selectionNew {
            get {
                object obj = ResourceManager.GetObject("zoom_selectionNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
