//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPluginSample {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppPluginSample.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 这是一个测试程序 的本地化字符串。
        /// </summary>
        internal static string btn_Description {
            get {
                return ResourceManager.GetString("btn_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内部插件 的本地化字符串。
        /// </summary>
        internal static string btn_Text {
            get {
                return ResourceManager.GetString("btn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这是一个测试程序 的本地化字符串。
        /// </summary>
        internal static string btn_Tooltip {
            get {
                return ResourceManager.GetString("btn_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图层插件菜单(&amp;T) 的本地化字符串。
        /// </summary>
        internal static string mnuAppPlugin3_Text {
            get {
                return ResourceManager.GetString("mnuAppPlugin3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件测试(&amp;A) 的本地化字符串。
        /// </summary>
        internal static string mnuItem_Text {
            get {
                return ResourceManager.GetString("mnuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件1(&amp;B) 的本地化字符串。
        /// </summary>
        internal static string subMnuItem1_Text {
            get {
                return ResourceManager.GetString("subMnuItem1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件2(&amp;B) 的本地化字符串。
        /// </summary>
        internal static string subMnuItem2_Text {
            get {
                return ResourceManager.GetString("subMnuItem2_Text", resourceCulture);
            }
        }
    }
}
